In [11]:
import numpy as np
import pandas as pd
import models
from database import engine, sessionDB
from nba_api.stats.static import players
from nba_api.stats.endpoints import playerawards

In [12]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [13]:
players= players.get_players()
#players

In [14]:
models.Base.metadata.create_all(bind=engine)

award testing and structure allat stuff

In [ ]:
#using lebron cus hes the goat
lebron = [p for p in players if p["full_name"].lower() == "lebron james"]
lebron = lebron[0] #de-listifying (dont do this in prod)
lebron_id = lebron["id"] #2544
lebron_awards = playerawards.PlayerAwards(player_id=lebron_id).get_data_frames()[0]

acronym_hmap = {
    "All-Defensive Team": "DEF",''
    "All-NBA": "NBA",
    "All-Rookie Team": "ROOK",
    "NBA All-Star": "AS",
    "NBA All-Star Most Valuable Player": "ASMVP",
    "NBA Champion": "CHAMP",
    "NBA Cup All-Tournament Team": "CUP",
    "NBA Cup Most Valuable Player": "CUPMVP",
    "NBA Finals Most Valuable Player": "FMVP",
    "NBA Most Valuable Player": "MVP",
    "NBA Player of the Month": "POTM",
    "NBA Player of the Week": "POTW",
    "NBA Rookie of the Month": "ROTM",
    "NBA Rookie of the Year": "ROTY",
}

all_nba_set = {"DEF", "NBA", "ROOK", "CUP"}

#gotta add stat champs + dpoy/dpom + cfmvp + cpoy + dunk/3pt contest + teammate oty + hustle player oty

clean_lebron_awards_df = lebron_awards[lebron_awards["DESCRIPTION"].isin(acronym_hmap)]
clean_lebron_awards_df = clean_lebron_awards_df.drop([
    "FIRST_NAME", 
    "LAST_NAME", 
    "CONFERENCE", 
    "TYPE", 
    "SUBTYPE1", 
    "SUBTYPE2", 
    "SUBTYPE3",
    "MONTH",
    "WEEK",
    "PERSON_ID",
    "TEAM"
], axis=1)

clean_lebron_awards_df["ALL_NBA_TEAM_NUMBER"] = clean_lebron_awards_df["ALL_NBA_TEAM_NUMBER"].fillna(0)
clean_lebron_awards_df = clean_lebron_awards_df.replace(r'^\s*$', 0, regex=True) 
#^ gets rid of empty strings

clean_lebron_awards_df["DESCRIPTION"] = clean_lebron_awards_df["DESCRIPTION"].map(acronym_hmap)
clean_lebron_awards_df["DESCRIPTION"] = clean_lebron_awards_df.apply(
    lambda r: f"{r['DESCRIPTION']}{r['ALL_NBA_TEAM_NUMBER']}" 
    if r['DESCRIPTION'] in all_nba_set else r['DESCRIPTION'], 
    axis=1
)

clean_lebron_awards_df

    DESCRIPTION ALL_NBA_TEAM_NUMBER   SEASON
0          DEF1                   1  2008-09
1          DEF1                   1  2009-10
2          DEF1                   1  2010-11
3          DEF1                   1  2011-12
4          DEF1                   1  2012-13
5          DEF2                   2  2013-14
6          NBA2                   2  2004-05
7          NBA1                   1  2005-06
8          NBA2                   2  2006-07
9          NBA1                   1  2007-08
10         NBA1                   1  2008-09
11         NBA1                   1  2009-10
12         NBA1                   1  2010-11
13         NBA1                   1  2011-12
14         NBA1                   1  2012-13
15         NBA1                   1  2013-14
16         NBA1                   1  2014-15
17         NBA1                   1  2015-16
18         NBA1                   1  2016-17
19         NBA1                   1  2017-18
20         NBA3                   3  2018-19
21         NBA1                   1  2019-20
22         NBA2                   2  2020-21
23         NBA3                   3  2021-22
24         NBA3                   3  2022-23
25         NBA3                   3  2023-24
26         NBA2                   2  2024-25
27        ROOK1                   1  2003-04
28           AS                   0  2004-05
29           AS                   0  2005-06
30           AS                   0  2006-07
31           AS                   0  2007-08
32           AS                   0  2008-09
33           AS                   0  2009-10
34           AS                   0  2010-11
35           AS                   0  2011-12
36           AS                   0  2012-13
37           AS                   0  2013-14
38           AS                   0  2014-15
39           AS                   0  2015-16
40           AS                   0  2016-17
41           AS                   0  2017-18
42           AS                   0  2018-19
43           AS                   0  2019-20
44           AS                   0  2020-21
45           AS                   0  2021-22
46           AS                   0  2022-23
47           AS                   0  2023-24
48           AS                   0  2024-25
49           AS                   0  2025-26
50        ASMVP                   0  2005-06
51        ASMVP                   0  2007-08
52        ASMVP                   0  2017-18
53        CHAMP                   0  2011-12
54        CHAMP                   0  2012-13
55        CHAMP                   0  2015-16
56        CHAMP                   0  2019-20
57         CUP1                   1  2023-24
58       CUPMVP                   0  2023-24
59         FMVP                   0  2011-12
60         FMVP                   0  2012-13
61         FMVP                   0  2015-16
62         FMVP                   0  2019-20
63          MVP                   0  2008-09
64          MVP                   0  2009-10
65          MVP                   0  2011-12
66          MVP                   0  2012-13
67         POTM                   0  2004-05
68         POTM                   0  2004-05
69         POTM                   0  2005-06
70         POTM                   0  2005-06
71         POTM                   0  2006-07
72         POTM                   0  2007-08
73         POTM                   0  2007-08
74         POTM                   0  2008-09
75         POTM                   0  2008-09
76         POTM                   0  2008-09
77         POTM                   0  2008-09
78         POTM                   0  2009-10
79         POTM                   0  2009-10
80         POTM                   0  2009-10
81         POTM                   0  2009-10
82         POTM                   0  2010-11
83         POTM                   0  2010-11
84         POTM                   0  2010-11
85         POTM                   0  2011-12
86         POTM                   0  2011-12
87         POTM                   0  2012-13
88         POTM                   0  2012-13
89         POTM                   0  2012-13
90         POTM                   0  2012-13
91         POTM                   0  2013-14
92         POTM                   0  2013-14
93         POTM                   0  2014-15
94         POTM                   0  2014-15
95         POTM                   0  2015-16
96         POTM                   0  2015-16
97         POTM                   0  2015-16
98         POTM                   0  2016-17
99         POTM                   0  2016-17
100        POTM                   0  2017-18
101        POTM                   0  2017-18
102        POTM                   0  2017-18
103        POTM                   0  2017-18
104        POTM                   0  2019-20
105        POTM                   0  2019-20
106        POTM                   0  2024-25
107        POTW                   0  2004-05
108        POTW                   0  2004-05
109        POTW                   0  2004-05
110        POTW                   0  2005-06
111        POTW                   0  2005-06
112        POTW                   0  2005-06
113        POTW                   0  2005-06
114        POTW                   0  2005-06
115        POTW                   0  2006-07
116        POTW                   0  2006-07
117        POTW                   0  2007-08
118        POTW                   0  2007-08
119        POTW                   0  2007-08
120        POTW                   0  2008-09
121        POTW                   0  2008-09
122        POTW                   0  2008-09
123        POTW                   0  2008-09
124        POTW                   0  2008-09
125        POTW                   0  2008-09
126        POTW                   0  2008-09
127        POTW                   0  2009-10
128        POTW                   0  2009-10
129        POTW                   0  2009-10
130        POTW                   0  2009-10
131        POTW                   0  2009-10
132        POTW                   0  2009-10
133        POTW                   0  2010-11
134        POTW                   0  2010-11
135        POTW                   0  2010-11
136        POTW                   0  2010-11
137        POTW                   0  2011-12
138        POTW                   0  2011-12
139        POTW                   0  2011-12
140        POTW                   0  2011-12
141        POTW                   0  2011-12
142        POTW                   0  2011-12
143        POTW                   0  2012-13
144        POTW                   0  2012-13
145        POTW                   0  2012-13
146        POTW                   0  2012-13
147        POTW                   0  2012-13
148        POTW                   0  2012-13
149        POTW                   0  2013-14
150        POTW                   0  2013-14
151        POTW                   0  2014-15
152        POTW                   0  2014-15
153        POTW                   0  2014-15
154        POTW                   0  2015-16
155        POTW                   0  2015-16
156        POTW                   0  2015-16
157        POTW                   0  2015-16
158        POTW                   0  2015-16
159        POTW                   0  2016-17
160        POTW                   0  2016-17
161        POTW                   0  2016-17
162        POTW                   0  2016-17
163        POTW                   0  2017-18
164        POTW                   0  2017-18
165        POTW                   0  2017-18
166        POTW                   0  2017-18
167        POTW                   0  2019-20
168        POTW                   0  2019-20
169        POTW                   0  2019-20
170        POTW                   0  2021-22
171        POTW                   0  2022-23
172        POTW                   0  2022-23
173        POTW                   0  2023-24
174        POTW                   0  2024-25
175        ROTM                   0  2003-04
176        ROTM                   0  2003-04
177        ROTM                   0  2003-04
178        ROTM                   0  2003-04
179        ROTM                   0  2003-04
180        ROTM                   0  2003-04
181        ROTY                   0  2003-04

actual award parsing

In [ ]:
def getAwards(pid: int):
    awards_df = playerawards.PlayerAwards(player_id=pid).get_data_frames()[0]

    acronym_hmap = {
        "All-Defensive Team": "DEF",''
        "All-NBA": "NBA",
        "All-Rookie Team": "ROOK",
        "NBA All-Star": "AS",
        "NBA All-Star Most Valuable Player": "ASMVP",
        "NBA Champion": "CHAMP",
        "NBA Cup All-Tournament Team": "CUP",
        "NBA Cup Most Valuable Player": "CUPMVP",
        "NBA Finals Most Valuable Player": "FMVP",
        "NBA Most Valuable Player": "MVP",
        "NBA Player of the Month": "POTM",
        "NBA Player of the Week": "POTW",
        "NBA Rookie of the Month": "ROTM",
        "NBA Rookie of the Year": "ROTY",
    }

    all_nba_set = {"DEF", "NBA", "ROOK", "CUP"}

    awards_df = awards_df[awards_df["DESCRIPTION"].isin(acronym_hmap)]
    awards_df = awards_df.drop([
        "FIRST_NAME", 
        "LAST_NAME", 
        "CONFERENCE", 
        "TYPE", 
        "SUBTYPE1", 
        "SUBTYPE2", 
        "SUBTYPE3",
        "MONTH",
        "WEEK",
        "PERSON_ID",
        "TEAM"
    ], axis=1)

    awards_df["ALL_NBA_TEAM_NUMBER"] = awards_df["ALL_NBA_TEAM_NUMBER"].fillna(0)
    awards_df = awards_df.replace(r'^\s*$', 0, regex=True) 
    #^ gets rid of empty strings

    awards_df["DESCRIPTION"] = awards_df["DESCRIPTION"].map(acronym_hmap)
    awards_df["DESCRIPTION"] = awards_df.apply(
        lambda r: f"{r['DESCRIPTION']}{r['ALL_NBA_TEAM_NUMBER']}" 
        if r['DESCRIPTION'] in all_nba_set else r['DESCRIPTION'], 
        axis=1
    )

    return awards_df.drop(["ALL_NBA_TEAM_NUMBER"], axis=1)

getAwards(2544)

    DESCRIPTION   SEASON
0          DEF1  2008-09
1          DEF1  2009-10
2          DEF1  2010-11
3          DEF1  2011-12
4          DEF1  2012-13
5          DEF2  2013-14
6          NBA2  2004-05
7          NBA1  2005-06
8          NBA2  2006-07
9          NBA1  2007-08
10         NBA1  2008-09
11         NBA1  2009-10
12         NBA1  2010-11
13         NBA1  2011-12
14         NBA1  2012-13
15         NBA1  2013-14
16         NBA1  2014-15
17         NBA1  2015-16
18         NBA1  2016-17
19         NBA1  2017-18
20         NBA3  2018-19
21         NBA1  2019-20
22         NBA2  2020-21
23         NBA3  2021-22
24         NBA3  2022-23
25         NBA3  2023-24
26         NBA2  2024-25
27        ROOK1  2003-04
28           AS  2004-05
29           AS  2005-06
30           AS  2006-07
31           AS  2007-08
32           AS  2008-09
33           AS  2009-10
34           AS  2010-11
35           AS  2011-12
36           AS  2012-13
37           AS  2013-14
38           AS  2014-15
39           AS  2015-16
40           AS  2016-17
41           AS  2017-18
42           AS  2018-19
43           AS  2019-20
44           AS  2020-21
45           AS  2021-22
46           AS  2022-23
47           AS  2023-24
48           AS  2024-25
49           AS  2025-26
50        ASMVP  2005-06
51        ASMVP  2007-08
52        ASMVP  2017-18
53        CHAMP  2011-12
54        CHAMP  2012-13
55        CHAMP  2015-16
56        CHAMP  2019-20
57         CUP1  2023-24
58       CUPMVP  2023-24
59         FMVP  2011-12
60         FMVP  2012-13
61         FMVP  2015-16
62         FMVP  2019-20
63          MVP  2008-09
64          MVP  2009-10
65          MVP  2011-12
66          MVP  2012-13
67         POTM  2004-05
68         POTM  2004-05
69         POTM  2005-06
70         POTM  2005-06
71         POTM  2006-07
72         POTM  2007-08
73         POTM  2007-08
74         POTM  2008-09
75         POTM  2008-09
76         POTM  2008-09
77         POTM  2008-09
78         POTM  2009-10
79         POTM  2009-10
80         POTM  2009-10
81         POTM  2009-10
82         POTM  2010-11
83         POTM  2010-11
84         POTM  2010-11
85         POTM  2011-12
86         POTM  2011-12
87         POTM  2012-13
88         POTM  2012-13
89         POTM  2012-13
90         POTM  2012-13
91         POTM  2013-14
92         POTM  2013-14
93         POTM  2014-15
94         POTM  2014-15
95         POTM  2015-16
96         POTM  2015-16
97         POTM  2015-16
98         POTM  2016-17
99         POTM  2016-17
100        POTM  2017-18
101        POTM  2017-18
102        POTM  2017-18
103        POTM  2017-18
104        POTM  2019-20
105        POTM  2019-20
106        POTM  2024-25
107        POTW  2004-05
108        POTW  2004-05
109        POTW  2004-05
110        POTW  2005-06
111        POTW  2005-06
112        POTW  2005-06
113        POTW  2005-06
114        POTW  2005-06
115        POTW  2006-07
116        POTW  2006-07
117        POTW  2007-08
118        POTW  2007-08
119        POTW  2007-08
120        POTW  2008-09
121        POTW  2008-09
122        POTW  2008-09
123        POTW  2008-09
124        POTW  2008-09
125        POTW  2008-09
126        POTW  2008-09
127        POTW  2009-10
128        POTW  2009-10
129        POTW  2009-10
130        POTW  2009-10
131        POTW  2009-10
132        POTW  2009-10
133        POTW  2010-11
134        POTW  2010-11
135        POTW  2010-11
136        POTW  2010-11
137        POTW  2011-12
138        POTW  2011-12
139        POTW  2011-12
140        POTW  2011-12
141        POTW  2011-12
142        POTW  2011-12
143        POTW  2012-13
144        POTW  2012-13
145        POTW  2012-13
146        POTW  2012-13
147        POTW  2012-13
148        POTW  2012-13
149        POTW  2013-14
150        POTW  2013-14
151        POTW  2014-15
152        POTW  2014-15
153        POTW  2014-15
154        POTW  2015-16
155        POTW  2015-16
156        POTW  2015-16
157        POTW  2015-16
158        POTW  2015-16
159        POTW  2016-17
160        POTW  2016-17
161        POTW  2016-17
162        POTW  2016-17
163        POTW  2017-18
164        POTW  2017-18
165        POTW  2017-18
166        POTW  2017-18
167        POTW  2019-20
168        POTW  2019-20
169        POTW  2019-20
170        POTW  2021-22
171        POTW  2022-23
172        POTW  2022-23
173        POTW  2023-24
174        POTW  2024-25
175        ROTM  2003-04
176        ROTM  2003-04
177        ROTM  2003-04
178        ROTM  2003-04
179        ROTM  2003-04
180        ROTM  2003-04
181        ROTY  2003-04