In [3]:
from nba_api.stats.endpoints import leaguestandings

In [ ]:
def getStandings(season: str):
    standings = leaguestandings.LeagueStandings(
        season = season,
        season_type = "Regular Season"
    )

    standings_df = standings.get_data_frames()[0]
    east_df, west_df = standings_df[standings_df["Conference"] == "East"], standings_df[standings_df["Conference"] == "West"]
    return east_df, west_df

standings = getStandings("2025-26")
standings[0] #1

   LeagueID SeasonID      TeamID      TeamCity  ...   Nov   Dec  PreAS  PostAS
1        00    22025  1610612765       Detroit  ...  13-2   9-4  60-22    None
2        00    22025  1610612738        Boston  ...   8-6   9-3  56-26    None
5        00    22025  1610612752      New York  ...  11-3  10-4  53-29    None
6        00    22025  1610612739     Cleveland  ...   9-6   7-7  52-30    None
9        00    22025  1610612761       Toronto  ...  12-3   6-8  46-36    None
10       00    22025  1610612737       Atlanta  ...  10-5  3-11  46-36    None
12       00    22025  1610612755  Philadelphia  ...   6-8   7-5  45-37    None
14       00    22025  1610612753       Orlando  ...  10-4   7-7  45-37    None
17       00    22025  1610612766     Charlotte  ...  4-11   5-8  44-38    None
19       00    22025  1610612748         Miami  ...  10-5   5-8  43-39    None
21       00    22025  1610612749     Milwaukee  ...  5-11   5-8  32-50    None
22       00    22025  1610612741       Chicago  ...  4-10   7-7  31-51    None
24       00    22025  1610612751      Brooklyn  ...  3-11   7-4  20-62    None
26       00    22025  1610612754       Indiana  ...  4-11  2-12  19-63    None
29       00    22025  1610612764    Washington  ...  1-12   6-8  17-65    None

[15 rows x 81 columns]

In [13]:
getStandings("2025-26")[1]

   LeagueID SeasonID      TeamID       TeamCity  ...   Nov   Dec  PreAS  PostAS
0        00    22025  1610612760  Oklahoma City  ...  14-1   9-4  64-18    None
3        00    22025  1610612759    San Antonio  ...   8-6  11-3  62-20    None
4        00    22025  1610612743         Denver  ...  11-3   9-5  54-28    None
6        00    22025  1610612747    Los Angeles  ...  11-2   5-7  53-29    None
9        00    22025  1610612745        Houston  ...  11-2   7-6  52-30    None
10       00    22025  1610612750      Minnesota  ...  10-5   9-5  49-33    None
13       00    22025  1610612756        Phoenix  ...  10-5   7-5  45-37    None
15       00    22025  1610612757       Portland  ...  4-10   6-8  42-40    None
17       00    22025  1610612746             LA  ...  2-13   6-6  42-40    None
19       00    22025  1610612744   Golden State  ...   7-8   7-6  37-45    None
21       00    22025  1610612740    New Orleans  ...  3-13   5-9  26-56    None
22       00    22025  1610612742         Dallas  ...  4-12   6-7  26-56    None
24       00    22025  1610612763        Memphis  ...   6-9   6-6  25-57    None
26       00    22025  1610612758     Sacramento  ...  4-12   3-9  22-60    None
28       00    22025  1610612762           Utah  ...  4-10   6-7  22-60    None

[15 rows x 81 columns]